[package]
name = "download"
version = "0.1.5"
authors = ["Xavier Stevens <xavier.stevens@gmail.com>"]

[dependencies]
clap = "2"
data-encoding = "2.1"
pbr = "1"
reqwest = "0.9"
hyper = "0.12"
ring = "0.13"

[profile.release]
lto = true
