[package]
name = "download"
version = "0.1.2"
authors = ["Xavier Stevens <xavier.stevens@gmail.com>"]

[dependencies]
clap = "2"
pbr = "1.0.0"
reqwest = "0.7"
rust-crypto = "0.2"

[profile.release]
lto = true
