[package]
name = "download"
version = "0.1.7"
authors = ["Xavier Stevens"]

[dependencies]
clap = "2.33.0"
data-encoding = "2.1"
pbr = "1.0.2"
reqwest = { version = "0.10.0", default-features = false, features = ["blocking", "rustls-tls"] }
hyper = "0.12"
digest = "0.8"
sha2 = "0.8"
sha-1 = "0.8"

[profile.release]
lto = true
